# Generated by Django 5.2.7 on 2025-10-17 14:05

import admission.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('guardian', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('education', models.CharField(blank=True, max_length=300)),
                ('exam_roll', models.CharField(blank=True, max_length=100)),
                ('program', models.CharField(choices=[('bachelors', 'Bachelors'), ('masters', 'Masters'), ('postgraduate', 'Postgraduate')], max_length=50)),
                ('fee_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='submitted', max_length=32)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('total_credits', models.PositiveIntegerField(default=0)),
                ('per_credit_fee', models.PositiveIntegerField(default=0)),
                ('seats', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'photo'), ('sign', 'sign'), ('transcript', 'transcript')], max_length=32)),
                ('file', models.FileField(upload_to=admission.models.app_media_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='admission.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admission.department'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(default='mock', max_length=64)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_data', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='admission.application')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('degrees', models.CharField(blank=True, max_length=256)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='admission.department')),
            ],
        ),
    ]
